### ISSUE TITLE
Implementation document

### ISSUE THREAD

**Issue by dezudas** [zoxxx/PhoneGap-KeepScreenOn-plugin#1]
I tried to implement it but it is not working form me could you please enhance the implementation document.

**Comment by zoxxx** [comment]
The plugin is quite simple.
Could you please send more info about the problem you're facing including some snippets of your implementation?
What PG/Cordova version you're using?

**Comment by dezudas** [comment]
Cordova version: 3.5.0-0.2.4

I just added the line "keepscreenon.enable();" in page load function

**Comment by zoxxx** [comment]
You should wait for Cordova's "deviceready" event but that's probably something you already did.

I'll test the plugin with 3.5.0-0.2.4 today, and I'll let you know. In the meantime could you please answer me on few questions.

Did you get any kind of error report in the console?
What OS (Android, iOS) versions you were using to test this plugin?
What phone/tablet model?

Thanks

**Comment by zoxxx** [comment]
I tested plugin on 3.5.0-0.2.4 and everything seems fine. Please let me know if you still have issues along with answers on my previous questions. Thanks.
